import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar"; 
import HeadLogo from "../components/HeadLogo"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Fixed Top Header */}
        <div className="fixed top-0 left-0 w-full h-[70px] z-50 bg-white shadow">
          <HeadLogo />
        </div>

        {/* Sidebar + Scrollable Main Content */}
        <div className="flex pt-[70px] h-screen">
          {/* Fixed Sidebar */}
          <div className="fixed top-[70px] left-0 h-[calc(100vh-70px)] w-72 bg-sky-400 z-40 shadow">
            <Navbar />
          </div>

          {/* Scrollable content with left padding to avoid overlapping sidebar */}
          <main className="ml-72 flex-1 overflow-y-auto h-[calc(100vh-70px)] p-6 bg-white">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
